export { circuitsDescription } from './circuits';
export { dcimDescription } from './dcim';
export { extrasDescription } from './extras';
export { ipamDescription } from './ipam';
export { statusDescription } from './status';
export { tenancyDescription } from './tenancy';
export { usersDescription } from './users';
export { virtualizationDescription } from './virtualization';
export { wirelessDescription } from './wireless';
